




.build/atmega328/src/serialBridge.cpp : src/serialBridge.ino
	@mkdir -p .build/atmega328/src
	@echo [93msrc/serialBridge.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/atmega328/src/serialBridge.cpp
	@true

